version: '2'

services:

  jenkins:
    image: ujiro99/cpp:latest
    container_name: jenkins
    tty: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/docker/src:/mnt/src
      - /home/docker/tmp:/mnt/tmp
      - /home/docker/src/github.com/ujiro99/docker-dev-env/jenkins:/var/jenkins_home
      - /home/docker/src/.gitconfig.local:/root/.gitconfig.local
      - /home/docker/src/.bashrc.local:/root/.bashrc.local
