version: '2'

volumes:
  data:
    driver: 'local'

services:
  samba:
    image: dperson/samba
    container_name: dev_samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - data:/mnt/work
    command: "-s work;/mnt/work;yes;yes;yes;foo;foo;foo -u foo;bar"

  python:
    image: ujiro99/python
    container_name: dev_python
    tty: true
    volumes:
      - data:/mnt/work
      - /home/docker/downloads:/mnt/downloads
      - /home/docker/share:/mnt/share
      - /home/docker/src:/mnt/src
      - /home/docker/tmp:/mnt/tmp
      - /home/docker/src/.gitconfig.local:/root/.gitconfig.local
      - /home/docker/.bashrc.local:/root/.bashrc.local
    command: "/bin/sh"

