version: '2'

services:

  python:
    image: ujiro99/python
    container_name: python
    tty: true
    volumes:
      - /home/docker/src:/mnt/src
      - /home/docker/tmp:/mnt/tmp
      - /home/docker/src/.gitconfig.local:/root/.gitconfig.local
      - /home/docker/src/.bashrc.local:/root/.bashrc.local
    command: "/bin/sh"

  cpp:
    image: ujiro99/cpp
    container_name: cpp
    tty: true
    volumes:
      - /home/docker/src:/mnt/src
      - /home/docker/tmp:/mnt/tmp
      - /home/docker/src/.gitconfig.local:/root/.gitconfig.local
      - /home/docker/src/.bashrc.local:/root/.bashrc.local
    command: "/bin/sh"

