version: '2'

volumes:
  data:
    driver: 'local'

services:
  samba:
    image: dperson/samba
    container_name: dev_samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - data:/mnt/work
    command: "-s work;/mnt/work;no;no;no;foo -u foo;bar"

  python:
    image: ujiro99/python
    container_name: dev_python
    tty: true
    volumes:
      - data:/mnt/work
    command: "/bin/sh"

